# Generated by Django 5.2.5 on 2025-09-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='post',
            new_name='blog',
        ),
    ]
