# Generated by Django 5.2.5 on 2025-09-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_post_entry_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='blog',
            new_name='post',
        ),
    ]
